project:
  type: book
  resources: 
    - "robots.txt" # this file prevents web crawlers from scraping your content for training AI/LLMs.  Downloaded from https://github.com/ai-robots-txt/ai.robots.txt v1.2.0

execute: 
  freeze: auto #only important if your book includes executed code
  
book:
  title: "LNN-UCPH Handbook"
  search: true
  repo-url: https://github.com/LNN-UCPH/LNN-UCPH-Handbook
  repo-actions: [edit, issue]
  repo-link-target: "_blank" #makes issue and edit links open in a new window/tab 
  page-footer: 
    left: '© 2024 by PI_NAME <br> This work is licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1) {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}'
    right: 'Made with [Quarto](https://quarto.org/) using the [Lab Group Handbook Template](https://github.com/cct-datascience/group-handbook-template)'
  author: 
    - name: Melanie Ganz
      orcid: 0000-0002-9120-8098
    - name: Martin Nørgaard
      orcid: 0000-0003-2131-5688
    #add all contributors as additional authors
  date: today #updates date published based on last time it was edited
  chapters:
    - index.qmd #the landing page file *must* be called 'index.qmd'
    - contributing.qmd
    - lab_philosophy.qmd
    - onboarding.qmd
    - research-best-practices.qmd
    - data-resources.qmd
    - computational_resources.qmd
    - publishing.qmd
    - funding_resources.qmd

bibliography: references.bib

format:
  html:
    number-depth: 1
    link-external-newwindow: true
    theme: #bootswatch themes.  For other options check out https://bootswatch.com/
      light: flatly
      dark: darkly

editor: 
  markdown:
    wrap: sentence #Forces each sentence to be on its own line in source markdown, doesn't affect how it is rendered
